apiVersion: ENC[AES256_GCM,data:MLg=,iv:Db2lg6TaDKHsASy37HiBd04lwxzWnZXN+4q5tMKgIXs=,tag:28yDM2munV+qsc/dxbQR5Q==,type:str]
kind: ENC[AES256_GCM,data:1VWaqu3B,iv:2HFnvRzdnVq2fK8yl8RYAeNGzwWtxeFas89C+uDpowY=,tag:t3X98qtDzQ91/RbdBn11rw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:/lrLF+Nb63lnoHuBznEp8BdRutoAQ5V5Feg=,iv:5FOEl/hg6dfkN3Mg2gi2P36ESZkUvRQ/ZScPfXaknXg=,tag:stJ1aiont22GSgyYAfQoJg==,type:str]
    labels:
        app: ENC[AES256_GCM,data:TNr4KTa6bSPxmTmUIfPvc1Qp,iv:Q1cFk/SkkqCmJcJXgCqGHkNQXlhW4DbQNgdNbrQxF3k=,tag:nBd5fvPzRiM4sjQtpEdqXw==,type:str]
type: ENC[AES256_GCM,data:MUSBfY94,iv:Xb2Lx4YttT0XYEDzNTZ4GERufYkyjuLzNdS2698rtAE=,tag:TW3YkPcwP1uw00XmHaAtsg==,type:str]
data:
    #ENC[AES256_GCM,data:A19XTLgtb+tWtPETs8vH2yjjvekhXPsgUk1MMJA/r5qDeDDn1nkhYbeRQp9vPLfwQeY5,iv:Asjwn8xCDlROveZiid2CJCUcDeZPS4PHv3H3f3rTLBQ=,tag:WlrgbKYqMyKjvCPfu0F8HQ==,type:comment]
    #ENC[AES256_GCM,data:y7Fzimf/isZZPr7NH2fPUdx/9YQfP8CVFh+zpkMIqTn+Zhkzv0t5SEE1Y70Qww==,iv:6+F5A9xa+GRY+t3P2jtcFWG/RxR+hZfFyeIJbJ9RIxE=,tag:bqk6k1Eb/frsRiBo94QZUw==,type:comment]
    OPENAI_API_KEY: ENC[AES256_GCM,data:npEoGJYmAseix8fXt4Y+TsoBpYYKK4dDJravZj58ujnVsxDwfZmJ35HwoyPI/c7c5sh2PBP+2WMWE0OehAWPO05jfO3xCi87rTuLXp8Irctya9ZFRtc59fNgo/GZiirteunPDdatE60XDU/xI2MMg8siGTPV3Vu/LoCZ9Ma0eOzItLzz4PA3i4JxbJdJuqrKI2qqkDy6jN9yagSY711d8P7tT0j/xYKgZHH0j4rzsHP1Ycu/mAllWniVo/l+Nt6ufkVwzMeRbqbC2dvLmxbkTJ0U+KymZu7QlGB5IQ==,iv:/fX3C+b7bkGUpXEO2FWCUGRSbkYErRHNnhE8gl7TZ9w=,tag:mqky0uIYxeX6cUCzgqMFng==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:o5gZBTRnj2Dnt+k0Gxr37A0hyz9KFS1DEnSpj3OmiTcef9vTAkl0Ly848aWtZ+tkhK9kKdX2mqJS5FiIZ3Uj4tqtmYYI6ltwY5Hs9lP6m/8IPzYozNZagcmIgRsgbkGB8H/aiCBUfJp0V/OcWaEZoWoVuxTdTLbrYz2C34tVqe7Q+AroeZf4ROrFswG+dYrpZtlolAEStOZbIHn5CYysNydw6XI=,iv:+AofVbB2rTLJuyUve7QgA9/0v0rNt+aXqhl7l3IOERQ=,tag:MOu3kKVEqfK+t9CJzLaUWA==,type:str]
    QDRANT_API_KEY: ENC[AES256_GCM,data:vYU1WbJv2tqbFX9Ul1YD8tiCZQjlAxOuJabDuu3/dHYoa1zENV/ICFebyiCiZ16GWWJ/RqD9EjI8y4bzDumRLGXApgowqI5VqYaX/lSlAm+SW3rA8nw/48TOsgcKBmoq2gpqxc/isztWzkWtNOzcnviuUkwlQWfl1WEqEIm6dcIV/BzJfrmmfg==,iv:IWM23ZvibC+/sfWlrUJOGAXWVNoVRLcW03wkz4lGyPA=,tag:7+3omDwg96Uh1eB9pPMxjg==,type:str]
    SECRET_USER_ID: ENC[AES256_GCM,data:P7D3IGjFnJXMQm8+9uXzoJKEMSQ=,iv:WcydU/CsW7y/Ridoh27jAbIOTKXwTpSQJn3dYn+CoHY=,tag:0uJlEZZCDlf+yIhrdTcuPA==,type:str]
    GOOGLE_API_KEY: ENC[AES256_GCM,data:JLSlNgpXGv/pBwlCAaPA8PPmA2qV8DaJtBVLFy32rXBWxL+5LkeZXm505JXDaLxpsWlgrQ==,iv:x2NDc75nBO4Fcxm5gKQwQ/uvROJoXa+S8MNZbRoP2Bc=,tag:tPKgo4kZyP4nD2EbMbHITQ==,type:str]
sops:
    age:
        - recipient: age1alrmt6qp308t0ww7ud0pynxwk636vz7r9u6qr5cehsu7747acdts8aulky
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXektVTW4yNnZBd3lkdzVV
            akthSjExUzh1MS9nQnk4VGlrT2NJcmw5a0hrCjY0elN1NGFpQ29QV25YVXFtRS8x
            cHI4enYzSFV5MXk3SUk0STI4d0FKM2cKLS0tIFJwckxEU2Q5VnhlUGdQSnBua3lL
            ZndDcy9IV2ZjODNtK3BRWlg0S05kNjQKOokqAI9j5OA1B7kxyAeItx0kNrJx2V7O
            DYCdBjP4gW5wukHYtkaleEdAtgz3nZJgm3WuI1I39X8qLKfCCzsCNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-19T22:07:25Z"
    mac: ENC[AES256_GCM,data:TT+JYwlEX4lN078w9IMQtbHRAstv4cWhca7WGATCcXiiY3mrj2YKjxSW0XpAT5zcE+6d+fuAMgzcFfwn7V2q5NPdPa/3B9jgRIkek0Po91TcB+K3pR6Jr8SmHCuEEcFFTW49hWsJClZjrYgUAY8yi7PwZqpt2MCaMdmZQDjtX4E=,iv:r7UFDR940ObfkdTODyJlvKFuHBuk9YL/NseElf42u9c=,tag:3FbMCduoB0tq/BF8FdsgRA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
