apiVersion: ENC[AES256_GCM,data:rco=,iv:4XCPm9Atsawd6D/bDVx0oHLu3lmEOrytSuB/EgAfA1w=,tag:Lv9DJmnl3wepBVyuEwGP6g==,type:str]
kind: ENC[AES256_GCM,data:OMyuZ5TJ,iv:OPAxIYp0Hhxv1yJ4eF7o481lq/UFAweM6uxzzjzQEQA=,tag:qmHJQ6C3ivTAIUhXozZ9hw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:s/XgofB2XSp2lKwIz/JBkwYHdw186sXuhfE=,iv:fgh0zaM1wsbQkX+qPzJ2uFLx9ClDUm0gRH12qBSuALY=,tag:kFrrCQR+hyaTsuNNibj1fQ==,type:str]
    labels:
        app: ENC[AES256_GCM,data:mZB3obvov9MwEHTLO1egskxj,iv:xpkTT8hOz/XHlWaxNDKgnPevvcE4vueEKduTA0HpWho=,tag:p6K8NWImMO9ExWgOPMsk+g==,type:str]
type: ENC[AES256_GCM,data:klITQZM9,iv:bbiEV/pff9Cp/o/N2GFzaeNomLAKeh6mwrO/zg0FkRs=,tag:K/wviSewILtQBIgtVzt9cA==,type:str]
data:
    #ENC[AES256_GCM,data:NI6vG/2qUFrr52PDrotzGWG1eWeMA94b5zLI10mudFXSJrNGZ7mj5Pu+9z51AJOhUMla,iv:54S1imH5lFgZ1RRqF4hJ25nbdCH/0qzdBDOob/yOm78=,tag:Y7f4pPtj0IbiHBeyEQqkHg==,type:comment]
    #ENC[AES256_GCM,data:fH7AYb1QzmQnmIWJkC+ReJtZAB82Nhhu7p95Zobw2cLMdmxHAbcVFUc7gKuXRA==,iv:HW5A0pL3QlYdwzT/U+KSWbPN5XtXVArHe9kzoNSCNzU=,tag:UyZCxn3GxPiWafDYNC34KQ==,type:comment]
    OPENAI_API_KEY: ENC[AES256_GCM,data:0+iOXCDEgAs1Ujfyb62cD9vRgY+8gDbEg09kXqgw8P9SbHE/Xngwdu5grGwRQAKt7ez2SbjbfsCI4De3e8r2Atrq4vnnnG/MLvrnUjLSRKeVNzAC05DJ/LwPowHwhIzZol3oKod7B9qsSg3c6ddVpcFqBWbmRPasdfqQ2BD7DZZZVzIQYZOlXi+ni1y+xg7AP/zW1SjVJXY+6RVgDIbj5XXNf2IBBHozlCvA7YKjNGCewAwqT6TCu7OuexuJvf76ZZN8J9OeyYgWQiqQljaoc2xE5ZxEMi6FGGPQaA==,iv:4iGmLM+eQrnn/ZGMGBTvag6VEhOH6lOgxvtbn3tv+3A=,tag:gtlPCIxAV5oeZernVuWdrg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:y/26MR0G2BHDAE67g/UZCPiY5nV+qHXCfUe+wwgeVyNWcwezvTLaxCERy2JOUJdMjMbjm1V6FlPHetgmwq1rP/ogqa+gKWBfUYgooj7oD5TeEOMv77jiidCWxd7jB1tGwPGhuNT7Bxb6sbV+l5V9x0y10ICCkniN/b1esr3bLiDthVNbD5GorfZIkszf0AvEEJxBk6NVr/tKCUIAWmb53mGhrh0=,iv:PEujL9uKNld4Mmp4+ETmboNpd5vcNLPh65OHaYS8NvU=,tag:0g4Kex+admJV9SW78w7VpQ==,type:str]
    QDRANT_API_KEY: ENC[AES256_GCM,data:4aZhdtTmumhviHTKuikmjioZ1Come/UWPiyjGz5yUJliAmGfh0KdWcDNn8ifQPZOVWyz5cZVbbwhpaAoxxHBUogZqQAgNOkNLsXSFSNVjNHTn6iwpkPhyzovdTu5wRGFO+ET5lw4flT0wKpYoz2xOKBWzyAJd47oaC4L38IQs4yFMIZZ6X6Paw==,iv:OiIcheP4qqRRWZP/y/cHeWlqUU7zb9qxoKy0SwICDfw=,tag:mvYhmXi2Y7FrxfMT5TtnZg==,type:str]
    SECRET_USER_ID: ENC[AES256_GCM,data:9VGysiV2Ty+28u+h5nQ=,iv:pJBuN520efymEVa7E722WM/GwA50qMLObAwBq062JDk=,tag:Dleu2pw9tf67VO2rnOQ80Q==,type:str]
sops:
    age:
        - recipient: age1alrmt6qp308t0ww7ud0pynxwk636vz7r9u6qr5cehsu7747acdts8aulky
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRFRxTUFUZEM3eTA2bHQ2
            VmJpelRWcE56d1hwTjJBMHZjcEVRbGtrcFZnCmhOZU1vNkNHekgrQ1Y5L0NMcERh
            OXE4dVl6Yk1KUFI1Q2dMcHFOQnhVVFUKLS0tIHF1Vm1QeHBJWjl0VzI3NEVLT2JG
            Y1ZyUHFjWi9mcjh5OEM5a2pvQUFzV00KkaZQue4w1J6DaRZ5N5HmNRPSoMjHN0di
            ywVom6K0zdnq5ZIgVdnEFy7laolsDr+2IRlr/xzMlTYtfL7RRNmQhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-12T10:00:51Z"
    mac: ENC[AES256_GCM,data:6Ds7KNb670TMrGiH8noKmWiCY7BK3TlCKDafFD9BpTqhYDY1UjZiTWPn14TArgXkGJODepu++1sBWOivtk6bfPheJJxsdJKy6vRteJwopE9PNiYTTayrFkjdWI8T+chSxonkPYRsCR9iaBEWwNKqkYLBwIrq9CWd6d5I3zFA/x8=,iv:yw3/yXD+lzbwbVHH9qRRDnhYNz4URsnY9J+l2nz2aqg=,tag:DOQaYFdHwZU8/v7K2p6xhQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
