apiVersion: ENC[AES256_GCM,data:eVQ=,iv:qtWtmPnaOblPjos91VOmOOqMKGoerImieSumkBPoeTs=,tag:rvh9QqLPlOFXgJq8UEqB0w==,type:str]
kind: ENC[AES256_GCM,data:HdkkwfvQ,iv:5zJBuLuT3HyQsoTx/Dc4UdEGxVqwn6tidp97F970A/o=,tag:qI/Qz5S67cOhcV8j4Mc4OA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:bpwkq0TBZldqfCxGK9ULeqIVWZAQqvSGERQ=,iv:w1W2+SFr9ve1Q930nWKU9ptOK0HmfeqLD8DC3Kfhq1o=,tag:bO9AoLiVyKtNs6BRjWADCg==,type:str]
    labels:
        app: ENC[AES256_GCM,data:3eQYw2uyU1LQcuZNRZsAt+Xr,iv:ac0d4mm03Oo1cw3IAXmlywBJT3bhDcd0imH4lJFClcU=,tag:KRclZlLVP3jz/iQ6uB6g1w==,type:str]
type: ENC[AES256_GCM,data:H5sQFosM,iv:AKfz7X5ei2VvcjADHJJVufi+5Bmfuk2mxHVgY34zEAU=,tag:w5+8ZA4REbGNAe8oulmyMg==,type:str]
data:
    #ENC[AES256_GCM,data:D0Rdp0YnlN4mb1VCHyBRGFzFV34Y0hrm8lm8uP+70+FEGwErQUP9h1VgtgZRsH/GDKZF,iv:JNopLyxHl46OxbuXszaqstLmubBHjHXCEne2fgQYpeI=,tag:+CKe13pBpWzU3IqWxIvIfw==,type:comment]
    #ENC[AES256_GCM,data:6qYn/owzeF6pigwxn6CalnFFj9gCNl+VY0ihqlUMN43Oa54ZP3mRO3sXlKqWMg==,iv:sFHIVmEJTgTxUm4IJCGtNtTFwq7ARdt8qUUZGMEfEo0=,tag:Od7C6lNDuMKLaP+owDkiKw==,type:comment]
    OPENAI_API_KEY: ENC[AES256_GCM,data:e4FPxI0Zrlc0QIVA5asT6NNRj17WK59xtPg12uLTS5udq0WttGXsreijDkVVsNSWcEscLQTuQPG+d8x1aKXDtMcXle+MUNrV5q/ocOUITQVYbAVP4ChZdLbFLzXklRsizVRFi2mGLOVzjDwJacOw4n6jlKW5GJhRipS+KHyfWeYGAFlYtqjfBKMVF1sdiThtatfyETLQAMM1fAkHfUFo/md7dBC2XsWZ1eKm5MBa46zkeBLrASanqVVAn745lteupMPiGVqPT0UKkIEe/DreuMl0urq0BAtRAzrU0w==,iv:sz4R6y/BxBvBGrvoeYAj1kuzA3XAGhO9X08KiiTtrTM=,tag:W2M/fj5EnTpbnd4kRfurLQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:pFa5HvQH2bUKwzdpMvkCkunvVxu/ssw/k2N1QZi0OBDWhkvGK2SvvMzBxUQdDB2VnoFWZl2JLTGO+RTiu+spiN2Yw/uUu2VBjxpSdtlQRu+PMuafm3TJMdSZNe7aLWS4Z5YtZdchTUuyBjgxsLVHmYWEjjzQUzWGrJ684UhpKcL7EtTD2DtwMNmr0rfYRCz+kcEdZHHkjEHWQwY8FMJ/17H80t4=,iv:Jw7YYc4rq50S+wEA6r+r+VN/9yAO4DE/Zv9QR5Hydyk=,tag:3nv0MfnoqLNnCn0W/N2bNg==,type:str]
    QDRANT_API_KEY: ENC[AES256_GCM,data:vdsNtufrLhdDQwonFf+hmYexUuk3/uznLW8bcJNfIHSDzOh9LATV2lTehYSDPP88c5qnJgSjV++VyqA6aZ/sQbM6kRgfnqsBVoOMsFSfCTC34aWDLHSps8i5PkuRb7kuSNM3jPzPLSCmU8nU3HbwnDBn39RLcC+749TstAlqCLmn13+Wn81FpA==,iv:Ln0y02wAedWcewCUbZgHuFAdsoba+heQ3y9ay80FZk4=,tag:ijmSjanYKSdbyaVvdsz/aQ==,type:str]
    SECRET_USER_ID: ENC[AES256_GCM,data:AGKLbR/vW/k0MnW7Y+15daiqU6U=,iv:+ZsB3G6OXF55+jcwpVh2BWUmd9BT3SAWi8UPDUFWNro=,tag:lfSJAFiVAfwuPMOGK3LZUg==,type:str]
sops:
    age:
        - recipient: age1alrmt6qp308t0ww7ud0pynxwk636vz7r9u6qr5cehsu7747acdts8aulky
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicjVUbFZwdzFLTS9hSkVn
            cGZxbGtRTTRyWTlPRjZzZ0dKekd1WTgrNDJnCmhRRVN4LzdHMmpkODVuQnBoY2RO
            VlZNT3F6VnNoSWQxNGhSV0pCcCtwcHcKLS0tIDZHRnpYYVFZRHlYZCtpbXBFNFky
            bUJ4alhERWw0UmhhTlllTkFjMEU2cFkKMxxDxE5yN168VFYOrYVl4BHLGU8qdOfj
            BkGmQfO3ErYcvG9BNm9JCzeHdNP8YM7CAeHN+sZtc7IFr3S6bWcRGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-12T10:59:38Z"
    mac: ENC[AES256_GCM,data:Bk5rI0JuHiOHf1DqJT06m8CWVdM9RUzo2PT5Z1sXiV6fadC1hBkkwMjG6vkykOvp5v28+9m2d9nJp6fYw3JW6fbFVLomrLO21rqKK3KMSjdDZvlWy2uquW13ZG8p9YNSrUpv4R6h4svefdfQk4ZOt8o1Z6uY8K4CrLUQqmROtSQ=,iv:YR9t0yAFlSoRwJo7rjDIG6Kx4WmnOAiOiWaSNUY4ET8=,tag:MmRwj1x3wKzZEt3mX2u14g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
