apiVersion: ENC[AES256_GCM,data:hVY=,iv:iL1sT0F03aauLbYyaOaRrwOmHJKlCJXazRlod+Jwl88=,tag:3T67MwI3Utp0G8TSCYmgvA==,type:str]
kind: ENC[AES256_GCM,data:zqCcj2ch,iv:/TQWq0bcYFwlNNx1h9+YWgX6pI5NdRQUHJkIIfv9Aak=,tag:re/20iXgYjVWyG146ulomw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:2Xs8ed5nF+p1YBt4yPZ1CrYsfK2IQ32vpco=,iv:AGKAFJrmbF31KHZPwnKUpvFy12F2wpqetOOG0Mee2Zs=,tag:8YA6RVWBzNOeodbW8Umemg==,type:str]
    labels:
        app: ENC[AES256_GCM,data:7lvkmWqGJlMV6HORYtwEy0zY,iv:xDpdSqhkd8P3+FeDYywb6dfbB3BgQ6npjhfJFaR3ewc=,tag:dYf5p0FQyRVNHJmoGEzvLA==,type:str]
type: ENC[AES256_GCM,data:HpjXfwKF,iv:kGmbVRIUwDguNTmba1HIFMIVokVm9OxAD/35nTiJw2k=,tag:+yUBSs7LmewA7Xn8GqoR6Q==,type:str]
data:
    #ENC[AES256_GCM,data:ZYXHQghqL4HKjrH+TDYW9lS6Irbg35VQRCwcGQIxcpH4jne+TuNJwNGJ9mhcwaMuE+Ra,iv:06jqBbO8ICv0A1Uqhzyx8ZkWxRGqNNKkg7g564JNH5I=,tag:jgartVHg0BdZtfD1yZhd7g==,type:comment]
    #ENC[AES256_GCM,data:VQF81wFOyI0z3E6XgdavDuxcPvzSIiNK+UZOtmInN5q/FFFyRCaILizV35oZAA==,iv:+AF9qjr1BCE2OgSOoiCEs6VjMkPO0JF/D5/5iY7Q9Tc=,tag:TzfonwXyLocY245TQCwGiQ==,type:comment]
    OPENAI_API_KEY: ENC[AES256_GCM,data:Yu5WZ9mC25IA6hUrIPsK7Lz57X0V6oOIDF9Fo8/kV4xk/RQP7WF8Ga5jCoxY8GVCusd7bNQxyzQORx6cl/5z7eUp1nv4jl5Er3ra+wXXTHUn0wG5KpWyXbUIgPb6IU2YRIUGDDRd2KVY4NmfebR4UxgxythhJLD9Tki2n+Ggj5/mvzNfLn6dCrLtLdjMA0WoJvmc/bJZA/lfxDwNlCevdWAA4sbVZ9d+SvMCGqH+32BS8wQ/dIC5ECY6hOFLmTdBqCRjDoDa/XnXAq6nUS/3DkfJ1hJ0uIcl+6OaJg==,iv:PVvzqjIZ701/+yiTvsmR4b26g9dAYbYcGN/uD5U81u4=,tag:KfSGm1IInK1CvxerTpONZQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:aR2rztKjRc7nnw4IWvRMxRQBweZEcV0m7dV3PtO0uU2pbzMqduTPKjEz7N3wk51IkqmPOnvru8D8818gQxsIZzUPgi2OxDvjp5DxwDZ6uKaWv+EhfxrGnkXv8BEmQIt3KQE3QY5YAIkz3O0GvNdEabR31ulIKODpHwjUvL57fwdi9cTfcLdsEHQuYWJ0xx7CFdBd3jcuoxLrDmi2A+LJwD4Z880=,iv:0BmQRt+JOYpD17Ft5RyGTYM3OQlPBswMWupMIdOyEa0=,tag:4DZYKagXNk5VsIRSISsvEQ==,type:str]
    QDRANT_API_KEY: ENC[AES256_GCM,data:ngWg+n1RzzjylStDud5qy5GSRCVUAqsqPmKk0OFONNSMJRKTbmSSaBjnMWtFBmUBcNBONfr+3Y397wMrH+Jey7mNTu95ju5a8D0drILFf6j4Ox6QaWkMycu7tj20z9zbdnAL/rGE9bSCS8tCSDvczcRt+c35kamJvepXsTDWltodHiOkSsShkw==,iv:s4t6YkCVIGqZTgGKQIyoIfvwCGQ0mpUInbu/5vP86pw=,tag:DFfoxZSewQV6nvQmwCzlxw==,type:str]
    SECRET_USER_ID: ENC[AES256_GCM,data:6s1q5ONjesHDRLmeSBB5ObI+S9k=,iv:FvgzvbZiFTwX0Z/z+aQIyVaJtCKd/h3K+magSRjzwwM=,tag:L0LlCkqnjTyz6sQ/0E4yeA==,type:str]
sops:
    age:
        - recipient: age1alrmt6qp308t0ww7ud0pynxwk636vz7r9u6qr5cehsu7747acdts8aulky
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoM1lSVW5vKy9CbHZoR2sx
            QW9ka2NXRzIzQjdXV29wT2QyVzMrSzM2U3dFCnNIb2lENG5DczdhTFIxUDUwa2pz
            K21GbWt6NUF3R2RWQjhlREYzMDVNelkKLS0tIHpvN1lYQWt3S0Q0dHduUVFpRjVI
            WkxSS1MvYU1PWklkNUpYbDJQNEFGSnMKvfAiGBlwBJsc421O8U1FZsXB83BLW7zd
            R3bbh8FoVKNpePDncEf+YapalKBh3YoDvLdk5nYztqyNV2zP/0YIYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-12T10:14:55Z"
    mac: ENC[AES256_GCM,data:Kd5kHVXo03W450a9rzskJfML//t/OM5tO0flX5Xh4P+hMkU7aXhaRCnXiWaTiTMsXAdlZYeeZxPllYsvZAOSHiGjV79CwvwG8L+qHqA2RJYSy0q4/2AAoFQ+FRfMEGA9NyBxnxKu26Pw8WJH5RGCUzuYiIcchg8ocQAL7p0Uk+E=,iv:w97H0YQ93yz8cZ+UYwkd2eW5iofJwnuxi0zFiuO6BlQ=,tag:kTP1XTVEZNRohixXuuampg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
